### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by moster67** [davinctor/CompileFFmpegWithOpenSSL#7]
Thank you for this. I will try and see if I can generate the libs. 
Do you think the libs generated will be compatible (out of the box) with WritingMinds app (see https://github.com/WritingMinds/ffmpeg-android-java)?
I'd like to get openSSL working.

**Comment by davinctor** [comment]
Hi @moster67. Thanks for your interest. 
My script won't generate single binary with packed other libraries (like avcodec swresample, etc) in one single binary. (not like [this](https://github.com/WritingMinds/ffmpeg-android-java/tree/master/FFmpegAndroid/assets/armeabi-v7a)). 
But this goal is in my roadmap for this repository. But it won't be available soon, that's why I suggest to you to experiment with it by yourself.

**Comment by moster67** [comment]
Thank you for your comments.
I will try.
